Algoritmo "TesteVetor"
// Disciplina   : Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2022
Var
V: Vetor[1..6] de Inteiro
C:Inteiro

Inicio
  Para C <- 1 ate 6 faca
    Escreva("Digite o ", C, " º valor ")
    Leia (v[c])
  FimPara
  
  Para C <- 1 ate 6 faca
     Escreva("{", v[c], "}")
  
  FimPara


Fimalgoritmo